package com.example.fitnesstracker.data.firebase

import com.example.fitnesstracker.data.WorkoutSession
import com.google.firebase.Timestamp
import java.util.Date

/**
 * Utility class to convert between Room WorkoutSession and FirestoreWorkoutSession
 */
object WorkoutSessionConverter {
    /**
     * Convert Room WorkoutSession to FirestoreWorkoutSession
     * Note: userId needs to be converted from Long (Room) to String (Firebase UID)
     */
    fun toFirestore(
        roomSession: WorkoutSession,
        firebaseUid: String
    ): FirestoreWorkoutSession {
        return FirestoreWorkoutSession(
            id = "", // Will be generated by Firestore
            userId = firebaseUid,
            exerciseId = roomSession.exerciseId?.toString(),
            workoutType = roomSession.workoutType,
            date = Timestamp(roomSession.date),
            totalReps = roomSession.totalReps,
            avgTempo = roomSession.avgTempo,
            formScore = roomSession.formScore,
            goalReps = roomSession.goalReps,
            duration = roomSession.duration,
            feedbackType = roomSession.feedbackType,
            avgElbowAngle = roomSession.avgElbowAngle,
            avgHipAngle = roomSession.avgHipAngle,
            goodFormPercentage = roomSession.goodFormPercentage,
            notes = roomSession.notes
        )
    }

    /**
     * Convert FirestoreWorkoutSession to Room WorkoutSession
     * Note: userId needs to be converted from String (Firebase UID) to Long (Room User ID)
     */
    fun toRoom(
        firestoreSession: FirestoreWorkoutSession,
        roomUserId: Long
    ): WorkoutSession {
        return WorkoutSession(
            id = 0, // Will be auto-generated by Room
            userId = roomUserId,
            exerciseId = firestoreSession.exerciseId?.toLongOrNull(),
            workoutType = firestoreSession.workoutType,
            date = firestoreSession.date.toDate(),
            totalReps = firestoreSession.totalReps,
            avgTempo = firestoreSession.avgTempo,
            formScore = firestoreSession.formScore,
            goalReps = firestoreSession.goalReps,
            duration = firestoreSession.duration,
            feedbackType = firestoreSession.feedbackType,
            avgElbowAngle = firestoreSession.avgElbowAngle,
            avgHipAngle = firestoreSession.avgHipAngle,
            goodFormPercentage = firestoreSession.goodFormPercentage,
            notes = firestoreSession.notes
        )
    }
}

